language: java
before_install:
  - chmod +x gradlew
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD '690922@Yd';" -U postgres

script:
  - ./gradlew build --info
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
deploy:
  provider: heroku
  api_key: 0732c0b2-dd50-4c92-9737-36dbef731950
  app: premhealthbabyservlet
services:
    - postgresql
